import React, { useState } from 'react';
import {
  X,
  Copy,
  Check,
  Award,
  BookOpen,
  AlertTriangle,
  Lightbulb,
  Clock,
  MessageSquare,
  Sparkles,
  Download,
  Volume2,
} from 'lucide-react';
import { SessionReport, TargetLanguage } from '../types';

interface ReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  report: SessionReport | null;
  isLoading: boolean;
  targetLanguage: TargetLanguage;
  onStartNewSession: () => void;
}

export const ReportModal: React.FC<ReportModalProps> = ({
  isOpen,
  onClose,
  report,
  isLoading,
  targetLanguage,
  onStartNewSession,
}) => {
  const [copied, setCopied] = useState(false);
  const [playingWord, setPlayingWord] = useState<string | null>(null);

  if (!isOpen) return null;

  const handleCopy = () => {
    if (!report) return;

    const formattedText = `# FluentPal Session Report: ${report.sessionStats?.targetLanguage || targetLanguage}
Date: ${new Date().toLocaleDateString()}
Estimated CEFR Level: ${report.estimatedCefrLevel}

## Overview
${report.summary}

## CEFR Level Assessment
${report.cefrReasoning}

## Top 3 Recurring Mistake Patterns
${report.topMistakePatterns
  .map(
    (p, i) => `${i + 1}. **${p.pattern}**
   - Example: "${p.example}"
   - Guidance: ${p.explanation}`
  )
  .join('\n\n')}

## Recommended Vocabulary & Idioms
${report.vocabulary
  .map(
    (v, i) => `${i + 1}. **${v.term}**: ${v.translationOrDefinition}
   - *Example:* "${v.exampleSentence}"`
  )
  .join('\n\n')}

## Practice Suggestions for Next Time
${report.practiceSuggestions.map((s, i) => `${i + 1}. ${s}`).join('\n')}

---
Duration: ${Math.round((report.sessionStats?.durationSeconds || 0) / 60)} min | Corrections: ${
      report.sessionStats?.correctionsCount || 0
    } | Turns: ${report.sessionStats?.turnsCount || 0}
`;

    navigator.clipboard.writeText(formattedText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownload = () => {
    if (!report) return;
    const element = document.createElement('a');
    const file = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' });
    element.href = URL.createObjectURL(file);
    element.download = `fluentpal-report-${new Date().toISOString().slice(0, 10)}.json`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const speakWord = (text: string) => {
    if (!('speechSynthesis' in window)) return;
    window.speechSynthesis.cancel();
    const utterance = new SpeechSynthesisUtterance(text);
    utterance.rate = 0.85;
    utterance.onstart = () => setPlayingWord(text);
    utterance.onend = () => setPlayingWord(null);
    utterance.onerror = () => setPlayingWord(null);
    window.speechSynthesis.speak(utterance);
  };

  return (
    <div
      id="report-modal-backdrop"
      className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-black/80 backdrop-blur-md animate-fadeIn"
      onClick={onClose}
    >
      <div
        id="report-modal-dialog"
        className="w-full max-w-3xl max-h-[92vh] flex flex-col bg-slate-900 border border-slate-700/80 rounded-2xl shadow-2xl overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-slate-900/95">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
              <Award className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-lg sm:text-xl font-bold text-white tracking-tight">Session Assessment & Progress</h2>
              <p className="text-xs text-slate-400">
                Detailed linguistic feedback generated by Gemini
              </p>
            </div>
          </div>
          <button
            id="close-report-btn"
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {isLoading ? (
            <div className="py-20 flex flex-col items-center justify-center text-center space-y-4">
              <div className="relative">
                <div className="w-14 h-14 rounded-full border-4 border-indigo-500/20 border-t-indigo-500 animate-spin" />
                <Sparkles className="w-6 h-6 text-indigo-400 absolute inset-0 m-auto animate-pulse" />
              </div>
              <div className="space-y-1">
                <h3 className="text-base font-semibold text-white">Analyzing Your Conversation...</h3>
                <p className="text-xs text-slate-400 max-w-sm">
                  Sam and Gemini are reviewing your pronunciation, grammar, vocabulary range, and CEFR level.
                </p>
              </div>
            </div>
          ) : report ? (
            <>
              {/* Top Highlight Banner: Estimated CEFR & Quick Stats */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="p-4 rounded-xl bg-gradient-to-br from-indigo-950/60 to-slate-900 border border-indigo-500/30 flex items-center gap-4">
                  <div className="w-14 h-14 rounded-2xl bg-indigo-500/20 border border-indigo-500/40 flex items-center justify-center text-indigo-300 font-extrabold text-2xl">
                    {report.estimatedCefrLevel}
                  </div>
                  <div>
                    <span className="text-xs uppercase tracking-wider text-indigo-400 font-semibold">Estimated CEFR</span>
                    <h4 className="text-sm font-bold text-white leading-tight">Proficiency Level</h4>
                    <p className="text-xs text-slate-400 mt-0.5">{report.sessionStats?.targetLanguage}</p>
                  </div>
                </div>

                <div className="p-4 rounded-xl bg-slate-800/60 border border-slate-700/60 flex items-center gap-4">
                  <div className="w-12 h-12 rounded-xl bg-slate-700/50 flex items-center justify-center text-slate-300">
                    <Clock className="w-6 h-6 text-amber-400" />
                  </div>
                  <div>
                    <span className="text-xs uppercase tracking-wider text-slate-400 font-medium">Spoken Duration</span>
                    <h4 className="text-base font-bold text-white">
                      {Math.max(1, Math.round((report.sessionStats?.durationSeconds || 0) / 60))} min
                    </h4>
                    <p className="text-xs text-slate-400">Live conversation</p>
                  </div>
                </div>

                <div className="p-4 rounded-xl bg-slate-800/60 border border-slate-700/60 flex items-center gap-4">
                  <div className="w-12 h-12 rounded-xl bg-slate-700/50 flex items-center justify-center text-slate-300">
                    <MessageSquare className="w-6 h-6 text-emerald-400" />
                  </div>
                  <div>
                    <span className="text-xs uppercase tracking-wider text-slate-400 font-medium">Logged Recasts</span>
                    <h4 className="text-base font-bold text-white">
                      {report.sessionStats?.correctionsCount || 0} corrections
                    </h4>
                    <p className="text-xs text-slate-400">{report.sessionStats?.turnsCount || 0} message turns</p>
                  </div>
                </div>
              </div>

              {/* Summary */}
              <div className="p-4 rounded-xl bg-slate-800/40 border border-slate-700/50 space-y-2">
                <h4 className="text-sm font-bold text-white flex items-center gap-2">
                  <Sparkles className="w-4 h-4 text-indigo-400" />
                  Tutor Summary
                </h4>
                <p className="text-sm text-slate-300 leading-relaxed">{report.summary}</p>
                <div className="pt-2 text-xs text-slate-400 border-t border-slate-700/30">
                  <span className="font-semibold text-slate-300">Assessment Note:</span> {report.cefrReasoning}
                </div>
              </div>

              {/* Top 3 Recurring Mistake Patterns */}
              {report.topMistakePatterns && report.topMistakePatterns.length > 0 && (
                <div className="space-y-3">
                  <h4 className="text-sm font-bold text-white flex items-center gap-2">
                    <AlertTriangle className="w-4 h-4 text-rose-400" />
                    Top 3 Focus Patterns to Improve
                  </h4>
                  <div className="grid grid-cols-1 gap-3">
                    {report.topMistakePatterns.map((m, idx) => (
                      <div
                        key={idx}
                        className="p-3.5 rounded-xl border border-rose-500/20 bg-rose-500/5 space-y-1.5"
                      >
                        <div className="flex items-center gap-2">
                          <span className="w-5 h-5 rounded-full bg-rose-500/20 text-rose-400 flex items-center justify-center text-xs font-bold">
                            {idx + 1}
                          </span>
                          <span className="font-semibold text-sm text-rose-200">{m.pattern}</span>
                        </div>
                        <div className="text-xs text-slate-300 pl-7">
                          <span className="text-slate-400">Example from chat: </span>
                          <span className="italic text-rose-300 font-mono">&ldquo;{m.example}&rdquo;</span>
                        </div>
                        <p className="text-xs text-slate-300 pl-7 leading-relaxed">{m.explanation}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Useful Vocabulary & Idioms */}
              {report.vocabulary && report.vocabulary.length > 0 && (
                <div className="space-y-3">
                  <h4 className="text-sm font-bold text-white flex items-center gap-2">
                    <BookOpen className="w-4 h-4 text-indigo-400" />
                    Key Vocabulary & Phrasal Idioms ({report.vocabulary.length})
                  </h4>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
                    {report.vocabulary.map((v, idx) => (
                      <div
                        key={idx}
                        className="p-3 rounded-xl border border-slate-700/60 bg-slate-800/60 space-y-1 hover:border-slate-600 transition-colors"
                      >
                        <div className="flex items-center justify-between">
                          <span className="font-semibold text-sm text-indigo-300">{v.term}</span>
                          <button
                            onClick={() => speakWord(v.term)}
                            title="Hear pronunciation"
                            aria-label={`Pronounce ${v.term}`}
                            className={`p-1 rounded text-slate-400 hover:text-indigo-400 hover:bg-slate-700/50 transition-colors ${
                              playingWord === v.term ? 'text-indigo-400 animate-pulse' : ''
                            }`}
                          >
                            <Volume2 className="w-3.5 h-3.5" />
                          </button>
                        </div>
                        <p className="text-xs text-slate-300 font-medium">{v.translationOrDefinition}</p>
                        <p className="text-xs italic text-slate-400 pt-0.5">
                          &ldquo;{v.exampleSentence}&rdquo;
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Next Practice Suggestions */}
              {report.practiceSuggestions && report.practiceSuggestions.length > 0 && (
                <div className="space-y-3">
                  <h4 className="text-sm font-bold text-white flex items-center gap-2">
                    <Lightbulb className="w-4 h-4 text-amber-400" />
                    3 Suggested Exercises for Your Next Session
                  </h4>
                  <div className="grid grid-cols-1 gap-2">
                    {report.practiceSuggestions.map((sug, idx) => (
                      <div
                        key={idx}
                        className="flex items-start gap-2.5 p-3 rounded-xl bg-amber-500/5 border border-amber-500/20 text-xs text-slate-200"
                      >
                        <span className="w-5 h-5 rounded-full bg-amber-500/20 text-amber-300 flex items-center justify-center font-bold shrink-0">
                          {idx + 1}
                        </span>
                        <span className="leading-relaxed pt-0.5">{sug}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </>
          ) : (
            <div className="py-12 text-center text-slate-400">
              No report available yet. Complete a conversation to generate an assessment.
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between px-6 py-4 border-t border-slate-800 bg-slate-900/90 gap-3">
          <div className="flex items-center gap-2">
            <button
              id="copy-report-btn"
              onClick={handleCopy}
              disabled={!report || isLoading}
              className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 active:scale-98 transition-all disabled:opacity-50"
            >
              {copied ? (
                <>
                  <Check className="w-4 h-4 text-emerald-400" />
                  <span className="text-emerald-400">Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" />
                  <span>Copy Report</span>
                </>
              )}
            </button>
            <button
              id="download-report-btn"
              onClick={handleDownload}
              disabled={!report || isLoading}
              className="hidden sm:flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700 transition-colors disabled:opacity-50"
            >
              <Download className="w-3.5 h-3.5" />
              <span>JSON</span>
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              id="close-report-secondary-btn"
              onClick={onClose}
              className="px-4 py-2 rounded-xl text-xs sm:text-sm font-medium text-slate-300 hover:bg-slate-800 transition-colors"
            >
              Close
            </button>
            <button
              id="practice-again-btn"
              onClick={() => {
                onClose();
                onStartNewSession();
              }}
              className="px-5 py-2 rounded-xl text-xs sm:text-sm font-semibold text-white bg-emerald-600 hover:bg-emerald-500 active:scale-98 transition-all shadow-lg shadow-emerald-600/20"
            >
              Practice Again
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
